version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10-browsers
    steps:
      - checkout
      - run:
          name: update-yarn
          command: 'yarn install'
      - run:
          name: test
          command: 'yarn test'
